server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
       # native:
       #   search-locations: "classpath:/config"
          #search-locations: "file:///Users//katar//Documents//config"
        git:
          uri: "https://github.com/Haripriya-511/easybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
encrypt:
  key: "ASDF12DG567UJMK08IJK"
